version: '3.8'

services:
  nginx:
    build: ./nginx
    restart: unless-stopped
    container_name: datamed-nginx
    ports:
      - "8080:80"

  nextjs:
    container_name: datamed-nextjs
    image: "datamed-nextjs"
    build:
      context: .
    env_file:
      - .env.production
    ports:
      - "80:80"
    #network_mode: "host"
