version: "3"

services:
  pg:
    image: postgres:14
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: datamed
      POSTGRES_USER: datamed
      POSTGRES_DB: datamed-clean
    volumes:
      - pg-volume:/var/lib/postgresql/data
volumes:
  db-pg-volume:
