version: '3.3'

services:
  postgres:
    # Official Postgres image from DockerHub
    image: 'postgres:14'
    env_file:
      - ./.env
      - ./.env.development
    volumes: # volume
      - ${POPULATE_HOST_DATA_PATH:?err}:/data
    ports:
      - 5432:5432
    networks:
      - app_net

networks:
  app_net:
    driver: bridge