version: '3.8'

services:
  nextjs:
    container_name: datamed
    image: "datamed"
    env_file:
      - ./.env.production
    ports:
      - "80:80"
    build:
      context: .

  nginx:
    image: nginx:1.22.1
    volumes:
      - /production/nginx/conf:/etc/nginx/conf.d:ro
      - /production/nginx/ssl/:/etc/nginx/ssl/:ro
    ports:
      - 443:443
    restart: always
