version: '3.8'

services:
  nginx:
    build: ./nginx
    restart: unless-stopped
    container_name: datamed-nginx
    ports:
      - "80:80"

  nextjs:
    container_name: datamed-nextjs
    build:
      context: .
    image: "datamed-nextjs"
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    network_mode: "host"
