version: '3.7'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"

  nextjs:
    build: ./
#    image: datamed-web:latest-prod
    environment:
      DEPLOY_ROOT_STRATEGY: LOCAL
      #DATABASE_URL_PROD: postgres://postgres:postgres@localhost:5432/datamed-local
      DATABASE_URL_DEV: postgres://ocddlxdxbfbegp:bc2f9130a2e68bf6184adebcfa38f6403ea6f6b745096bde36061bd2f7b8f181@ec2-63-34-180-86:eu-west-1:compute:amazonaws:com:5432/da31onm4ulch53
      NEXT_PUBLIC_WEB_PROD: https://data.ansm.sante.fr