version: '3.8'

services:
  app:
    container_name: datamed-app
    image: "ghcr.io/dataoffice-ansm/datamed:latest"
    platform: linux/amd64
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    #build:
    #  context: .

  nginx:
    container_name: datamed-nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    #volumes:
    #  - /production/nginx/conf:/etc/nginx/conf.d:ro
    #  - /production/nginx/ssl/:/etc/nginx/ssl/:ro
    depends_on:
      - app
    restart: always
